import { montserrat  } from '../assets/fonts';

export const metadata = {
  title: 'Eng-Alien',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="../images/logo.png" />
      </head>
      <body
        className={montserrat.className}
        style={{
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          margin: 0,
          overflowX: 'hidden',
        }}
      >{children}</body>
    </html>
  );
}
