export const metadata = {
  title: 'Home page',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        style={{
          width: '100%',
          height: '100%',
          display: 'flex',
          justifyContent: 'center',
          margin: 0,
          overflow: 'hidden',
        }}
      >{children}</body>
    </html>
  );
}
