import { dir } from '../../i18n/i18n-config';
import { montserrat } from '../../assets/fonts';
import I18nProvider from '../../components/Provider/I18nProvider';
import StoreProvider from '../../components/Provider/StoreProvider';

export const metadata = {
  title: 'Eng-Alien',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const currentLocale = params.locale;

  return (
    <html lang={currentLocale} dir={dir(currentLocale)}>
      <head>
        <link rel="icon" href="/images/logo.png" />
      </head>
      <body
        className={montserrat.className}
        style={{
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          margin: 0,
          overflowX: 'hidden',
        }}
      >
        <StoreProvider>
          <I18nProvider locale={currentLocale}>{children}</I18nProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
